import Cell.CellType

object Rules {
  val l: Cell.CellType = 'l'
  val x: Cell.CellType = 'x'
  val o: Cell.CellType = 'o'
  val v: Cell.CellType = 'v'
  val star: Cell.CellType = '*'

  val solveRules: List[Rule] = List(
  Rule(l, List(RuleCondition(-1, 1, x), RuleCondition(0, 1, o))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(-1, 0, o))),
  Rule(l, List(RuleCondition(0, -1, o), RuleCondition(1, -1, x))),
  Rule(l, List(RuleCondition(1, 0, o), RuleCondition(1, 1, x))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(0, -1, o))),
  Rule(l, List(RuleCondition(1, -1, x), RuleCondition(1, 0, o))),
  Rule(l, List(RuleCondition(0, 1, o), RuleCondition(1, 1, x))),
  Rule(l, List(RuleCondition(-1, 0, o), RuleCondition(-1, 1, x))),
  Rule(x, List(RuleCondition(-1, 1, l), RuleCondition(0, 1, o))),
  Rule(x, List(RuleCondition(-1, -1, l), RuleCondition(-1, 0, o))),
  Rule(x, List(RuleCondition(0, -1, o), RuleCondition(1, -1, l))),
  Rule(x, List(RuleCondition(1, 0, o), RuleCondition(1, 1, l))),
  Rule(x, List(RuleCondition(-1, -1, l), RuleCondition(0, -1, o))),
  Rule(x, List(RuleCondition(1, -1, l), RuleCondition(1, 0, o))),
  Rule(x, List(RuleCondition(0, 1, o), RuleCondition(1, 1, l))),
  Rule(x, List(RuleCondition(-1, 0, o), RuleCondition(-1, 1, l))),
  Rule(l, List(RuleCondition(0, 1, o), RuleCondition(0, 2, l))),
  Rule(l, List(RuleCondition(-2, 0, l), RuleCondition(-1, 0, o))),
  Rule(l, List(RuleCondition(0, -2, l), RuleCondition(0, -1, o))),
  Rule(l, List(RuleCondition(1, 0, o), RuleCondition(2, 0, l))),
  Rule(x, List(RuleCondition(-1, 0, v), RuleCondition(-1, 1, l), RuleCondition(0, 2, l))),
  Rule(x, List(RuleCondition(-2, 0, l), RuleCondition(-1, -1, l), RuleCondition(0, -1, v))),
  Rule(x, List(RuleCondition(0, -2, l), RuleCondition(1, -1, l), RuleCondition(1, 0, v))),
  Rule(x, List(RuleCondition(0, 1, v), RuleCondition(1, 1, l), RuleCondition(2, 0, l))),
  Rule(x, List(RuleCondition(-1, -1, l), RuleCondition(-1, 0, v), RuleCondition(0, -2, l))),
  Rule(x, List(RuleCondition(0, -1, v), RuleCondition(1, -1, l), RuleCondition(2, 0, l))),
  Rule(x, List(RuleCondition(0, 2, l), RuleCondition(1, 0, v), RuleCondition(1, 1, l))),
  Rule(x, List(RuleCondition(-2, 0, l), RuleCondition(-1, 1, l), RuleCondition(0, 1, v))),
  Rule(l, List(RuleCondition(-1, 0, v), RuleCondition(-1, 1, x), RuleCondition(0, 2, l), RuleCondition(1, 0, v), RuleCondition(1, 1, x))),
  Rule(l, List(RuleCondition(-2, 0, l), RuleCondition(-1, -1, x), RuleCondition(-1, 1, x), RuleCondition(0, -1, v), RuleCondition(0, 1, v))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(-1, 0, v), RuleCondition(0, -2, l), RuleCondition(1, -1, x), RuleCondition(1, 0, v))),
  Rule(l, List(RuleCondition(0, -1, v), RuleCondition(0, 1, v), RuleCondition(1, -1, x), RuleCondition(1, 1, x), RuleCondition(2, 0, l))),
  Rule(x, List(RuleCondition(-1, 0, v), RuleCondition(-1, 1, l), RuleCondition(1, 0, v), RuleCondition(1, 1, l))),
  Rule(x, List(RuleCondition(-1, -1, l), RuleCondition(-1, 1, l), RuleCondition(0, -1, v), RuleCondition(0, 1, v))),
  Rule(x, List(RuleCondition(-1, -1, l), RuleCondition(-1, 0, v), RuleCondition(1, -1, l), RuleCondition(1, 0, v))),
  Rule(x, List(RuleCondition(0, -1, v), RuleCondition(0, 1, v), RuleCondition(1, -1, l), RuleCondition(1, 1, l))),
  Rule(l, List(RuleCondition(0, 2, l), RuleCondition(0, 3, star))),
  Rule(l, List(RuleCondition(-3, 0, star), RuleCondition(-2, 0, l))),
  Rule(l, List(RuleCondition(0, -3, star), RuleCondition(0, -2, l))),
  Rule(l, List(RuleCondition(2, 0, l), RuleCondition(3, 0, star))),
  Rule(x, List(RuleCondition(0, 1, star), RuleCondition(0, 2, l))),
  Rule(x, List(RuleCondition(-2, 0, l), RuleCondition(-1, 0, star))),
  Rule(x, List(RuleCondition(0, -2, l), RuleCondition(0, -1, star))),
  Rule(x, List(RuleCondition(1, 0, star), RuleCondition(2, 0, l))),
  Rule(l, List(RuleCondition(0, 3, star), RuleCondition(0, 4, x))),
  Rule(l, List(RuleCondition(-4, 0, x), RuleCondition(-3, 0, star))),
  Rule(l, List(RuleCondition(0, -4, x), RuleCondition(0, -3, star))),
  Rule(l, List(RuleCondition(3, 0, star), RuleCondition(4, 0, x))),
  Rule(l, List(RuleCondition(0, 3, star), RuleCondition(0, 6, x))),
  Rule(l, List(RuleCondition(-6, 0, x), RuleCondition(-3, 0, star))),
  Rule(l, List(RuleCondition(0, -6, x), RuleCondition(0, -3, star))),
  Rule(l, List(RuleCondition(3, 0, star), RuleCondition(6, 0, x))),
  Rule(x, List(RuleCondition(0, 2, l), RuleCondition(0, 3, o), RuleCondition(0, 6, l))),
  Rule(x, List(RuleCondition(-6, 0, l), RuleCondition(-3, 0, o), RuleCondition(-2, 0, l))),
  Rule(x, List(RuleCondition(0, -6, l), RuleCondition(0, -3, o), RuleCondition(0, -2, l))),
  Rule(x, List(RuleCondition(2, 0, l), RuleCondition(3, 0, o), RuleCondition(6, 0, l))),
  Rule(x, List(RuleCondition(0, 3, o), RuleCondition(0, 4, l), RuleCondition(0, 6, l))),
  Rule(x, List(RuleCondition(-6, 0, l), RuleCondition(-4, 0, l), RuleCondition(-3, 0, o))),
  Rule(x, List(RuleCondition(0, -6, l), RuleCondition(0, -4, l), RuleCondition(0, -3, o))),
  Rule(x, List(RuleCondition(3, 0, o), RuleCondition(4, 0, l), RuleCondition(6, 0, l))),
  Rule(x, List(RuleCondition(0, 1, o), RuleCondition(0, 2, x))),
  Rule(x, List(RuleCondition(-2, 0, x), RuleCondition(-1, 0, o))),
  Rule(x, List(RuleCondition(0, -2, x), RuleCondition(0, -1, o))),
  Rule(x, List(RuleCondition(1, 0, o), RuleCondition(2, 0, x))),
  Rule(l, List(RuleCondition(0, 1, star), RuleCondition(0, 2, x))),
  Rule(l, List(RuleCondition(-2, 0, x), RuleCondition(-1, 0, star))),
  Rule(l, List(RuleCondition(0, -2, x), RuleCondition(0, -1, star))),
  Rule(l, List(RuleCondition(1, 0, star), RuleCondition(2, 0, x))),
  Rule(l, List(RuleCondition(0, 1, star), RuleCondition(0, 4, x))),
  Rule(l, List(RuleCondition(-4, 0, x), RuleCondition(-1, 0, star))),
  Rule(l, List(RuleCondition(0, -4, x), RuleCondition(0, -1, star))),
  Rule(l, List(RuleCondition(1, 0, star), RuleCondition(4, 0, x))),
  Rule(l, List(RuleCondition(0, 2, l), RuleCondition(0, 3, star))),
  Rule(l, List(RuleCondition(-3, 0, star), RuleCondition(-2, 0, l))),
  Rule(l, List(RuleCondition(0, -3, star), RuleCondition(0, -2, l))),
  Rule(l, List(RuleCondition(2, 0, l), RuleCondition(3, 0, star))),
  Rule(x, List(RuleCondition(0, -1, star), RuleCondition(0, 1, star))),
  Rule(x, List(RuleCondition(-1, 0, star), RuleCondition(1, 0, star))),
  Rule(x, List(RuleCondition(0, -1, o), RuleCondition(0, 1, o), RuleCondition(0, 3, o))),
  Rule(x, List(RuleCondition(-3, 0, o), RuleCondition(-1, 0, o), RuleCondition(1, 0, o))),
  Rule(x, List(RuleCondition(0, -3, o), RuleCondition(0, -1, o), RuleCondition(0, 1, o))),
  Rule(x, List(RuleCondition(-1, 0, o), RuleCondition(1, 0, o), RuleCondition(3, 0, o))),
  Rule(x, List(RuleCondition(0, -2, l), RuleCondition(0, 1, o), RuleCondition(0, 3, o))),
  Rule(x, List(RuleCondition(-3, 0, o), RuleCondition(-1, 0, o), RuleCondition(2, 0, l))),
  Rule(x, List(RuleCondition(0, -3, o), RuleCondition(0, -1, o), RuleCondition(0, 2, l))),
  Rule(x, List(RuleCondition(-2, 0, l), RuleCondition(1, 0, o), RuleCondition(3, 0, o))),
  Rule(x, List(RuleCondition(-1, 0, v), RuleCondition(-1, 1, x), RuleCondition(0, 2, x), RuleCondition(1, 0, v), RuleCondition(1, 1, x))),
  Rule(x, List(RuleCondition(-2, 0, x), RuleCondition(-1, -1, x), RuleCondition(-1, 1, x), RuleCondition(0, -1, v), RuleCondition(0, 1, v))),
  Rule(x, List(RuleCondition(-1, -1, x), RuleCondition(-1, 0, v), RuleCondition(0, -2, x), RuleCondition(1, -1, x), RuleCondition(1, 0, v))),
  Rule(x, List(RuleCondition(0, -1, v), RuleCondition(0, 1, v), RuleCondition(1, -1, x), RuleCondition(1, 1, x), RuleCondition(2, 0, x))),
  Rule(l, List(RuleCondition(-1, 0, v), RuleCondition(-1, 1, l), RuleCondition(0, 2, x), RuleCondition(1, 1, x))),
  Rule(l, List(RuleCondition(-2, 0, x), RuleCondition(-1, -1, l), RuleCondition(-1, 1, x), RuleCondition(0, -1, v))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(0, -2, x), RuleCondition(1, -1, l), RuleCondition(1, 0, v))),
  Rule(l, List(RuleCondition(0, 1, v), RuleCondition(1, -1, x), RuleCondition(1, 1, l), RuleCondition(2, 0, x))),
  Rule(l, List(RuleCondition(-1, -1, l), RuleCondition(-1, 0, v), RuleCondition(0, -2, x), RuleCondition(1, -1, x))),
  Rule(l, List(RuleCondition(0, -1, v), RuleCondition(1, -1, l), RuleCondition(1, 1, x), RuleCondition(2, 0, x))),
  Rule(l, List(RuleCondition(-1, 1, x), RuleCondition(0, 2, x), RuleCondition(1, 0, v), RuleCondition(1, 1, l))),
  Rule(l, List(RuleCondition(-2, 0, x), RuleCondition(-1, -1, x), RuleCondition(-1, 1, l), RuleCondition(0, 1, v))),
  Rule(l, List(RuleCondition(0, 1, star), RuleCondition(0, 5, o), RuleCondition(0, 7, o))),
  Rule(l, List(RuleCondition(-7, 0, o), RuleCondition(-5, 0, o), RuleCondition(-1, 0, star))),
  Rule(l, List(RuleCondition(0, -7, o), RuleCondition(0, -5, o), RuleCondition(0, -1, star))),
  Rule(l, List(RuleCondition(1, 0, star), RuleCondition(5, 0, o), RuleCondition(7, 0, o))),
  Rule(l, List(RuleCondition(1, -3, l), RuleCondition(1, 0, o), RuleCondition(1, 3, l))),
  Rule(l, List(RuleCondition(-3, 1, l), RuleCondition(0, 1, o), RuleCondition(3, 1, l))),
  Rule(l, List(RuleCondition(-1, -3, l), RuleCondition(-1, 0, o), RuleCondition(-1, 3, l))),
  Rule(l, List(RuleCondition(-3, -1, l), RuleCondition(0, -1, o), RuleCondition(3, -1, l))),
  Rule(l, List(RuleCondition(-1, 2, o), RuleCondition(0, 1, star), RuleCondition(1, 2, o))),
  Rule(l, List(RuleCondition(-2, -1, o), RuleCondition(-2, 1, o), RuleCondition(-1, 0, star))),
  Rule(l, List(RuleCondition(-1, -2, o), RuleCondition(0, -1, star), RuleCondition(1, -2, o))),
  Rule(l, List(RuleCondition(1, 0, star), RuleCondition(2, -1, o), RuleCondition(2, 1, o))),
  Rule(x, List(RuleCondition(0, 2, l), RuleCondition(0, 3, o), RuleCondition(0, 5, o))),
  Rule(x, List(RuleCondition(-5, 0, o), RuleCondition(-3, 0, o), RuleCondition(-2, 0, l))),
  Rule(x, List(RuleCondition(0, -5, o), RuleCondition(0, -3, o), RuleCondition(0, -2, l))),
  Rule(x, List(RuleCondition(2, 0, l), RuleCondition(3, 0, o), RuleCondition(5, 0, o)))
  )

  val contradictionRules: List[Rule] = List(
  Rule(l, List(RuleCondition(-1, 1, x), RuleCondition(0, 1, star), RuleCondition(1, 1, x))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(-1, 0, star), RuleCondition(-1, 1, x))),
  Rule(l, List(RuleCondition(-1, -1, x), RuleCondition(0, -1, star), RuleCondition(1, -1, x))),
  Rule(l, List(RuleCondition(1, -1, x), RuleCondition(1, 0, star), RuleCondition(1, 1, x)))
  )
}